// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsKqVM7iSngXB8YEcWTlbPd2jKqNaNKAQ',
    appId: '1:556038161304:web:545f4e795366befff2e1ed',
    messagingSenderId: '556038161304',
    projectId: 'flutter-56fba',
    authDomain: 'flutter-56fba.firebaseapp.com',
    storageBucket: 'flutter-56fba.appspot.com',
    measurementId: 'G-J6F1KE1BHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzkUH1H12nFEpS1lM7-EW0eCo2uE01uQ',
    appId: '1:556038161304:android:c83e3e34f713bb7ef2e1ed',
    messagingSenderId: '556038161304',
    projectId: 'flutter-56fba',
    storageBucket: 'flutter-56fba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeB3vZ--Jfd0aelnEB-QbH382aKhJCMZg',
    appId: '1:556038161304:ios:b9e5ee0bf52540acf2e1ed',
    messagingSenderId: '556038161304',
    projectId: 'flutter-56fba',
    storageBucket: 'flutter-56fba.appspot.com',
    iosBundleId: 'com.example.responsibel',
  );
}
